NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
BaltimoreLA <- subset(NEI, fips == "24510"|fips =="06037")
BaltimoreLA <- subset(BaltimoreLA, type == "ON-ROAD")
library(ggplot2)
png("plot6.png")
p <-ggplot(BaltimoreLA, aes(year, Emissions))
p+geom_point(aes(color = fips),alpha = .1)+geom_smooth(method = "lm")+facet_grid(facets = fips~.)+coord_cartesian(ylim = c(0,300))
dev.off()
