NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
Baltimore <- subset(NEI, fips == "24510")
Baltimore <- subset(Baltimore, type == "ON-ROAD")
SCC <- subset(SCC, Data.Category == "Onroad")
mergedBaltimore <- merge(Baltimore, SCC, by.x = 'SCC', by.y = 'SCC')
library(ggplot2)
png("plot5.png")
p <-ggplot(mergedBaltimore, aes(year, Emissions))
p+geom_point(aes(color = SCC.Level.Two),alpha = .1)+geom_smooth(method = "lm")+facet_grid(facets = SCC.Level.Two~.)+coord_cartesian(ylim = c(0,40))
dev.off()